spring:
    profiles:
        default: local
    application:
        name: server

    flyway:
        enabled: true
        locations: classpath:db/migration

    exposed:
        generate-ddl: false
